# encoding: utf-8

entidade = EntidadeEquipamento.create! :descricao => 'A associação possui cineclube, biblioteca, sarau literário, escola de esportes e telecentro. Também trabalha com as liguagens do HipHop',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '8421-2882  / betoaesp@hotmail.com / betoaesp@gmail.com',
                            :logradouro  => 'SR 21 L. 5 - Vale do Amanhecer',
                            :complemento => ' ,  ',
                            :estado    => 'DF',
                            :nome      => 'Ação Esperança (AESP)',
                            :email     => 'acaoesperanca@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Hip-Hop.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=cOW8xbgw4Lg',
                            :latitude  => -15.6770183,
                            :longitude => -47.6530577,
                            :user_id  => 1,
                            :atividade_id  => 1,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Cursos de cenotécnica, luminotécnica, contra-regra, adereço, bilheteria e portaria',
                            :site            => ' ',
                            :cep             => '70254-400',
                            :contato     => '3443-0606',
                            :logradouro  => 'EQS 208/209',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura ESTEC - Estúdio De Tecnologia Cênica',
                            :email     => 'nac@nac@org.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=oofn8PDVPq4',
                            :latitude  => -15.8203196572584,
                            :longitude => -47.9030486941338,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de audiovisual e áreas ligadas a comunicação',
                            :site            => 'http://mundoolharessaberes.blogspot.com',
                            :cep             => '71570-401',
                            :contato     => '8433-3282',
                            :logradouro  => 'CEM 01- Q 04 Cj A Área Especial - Paranoá',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Mundo, Olhares E Saberes - Associação Faísca Cultural',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=JkMs_1MrLiY',
                            :latitude  => -15.7833903307149,
                            :longitude => -47.7794659137726,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Grupo de quadrilha junina que possui trabalhos com artesanato e dança ',
                            :site            => ' ',
                            :cep             => '71573-101',
                            :contato     => '8125-2358',
                            :logradouro  => 'Q. 31 Cj. A C. 18',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Artnoá',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=h6H96e7se-0',
                            :latitude  => -15.7616564609382,
                            :longitude => -47.7813059091568,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Coletivo de Artistas que trabalha com artes visuais (grafite e design) - cursos, oficinas e projetos gráficos',
                            :site            => 'www.gruporua.com.br',
                            :cep             => '72215-042',
                            :contato     => '3965-9404',
                            :logradouro  => 'QNM 03 Cj. L Lt. 1 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Reunião Urbana De Artistas (Grupo RUA)',
                            :email     => 'studio@gruporua.com.br',
                            :imagem    => File.open('db/imagens/Hip-Hop.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=QmrRNO9r5CY',
                            :latitude  => -15.8233157239818,
                            :longitude => -48.1031388044357,
                            :user_id  => 1,
                            :atividade_id  => 1,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Cultura Popular, confecção de instrumentos e figurino, oficinas de percussão
',
                            :site            => 'www.seuestrelo.arte.br',
                            :cep             => '70200-130',
                            :contato     => '8114-1520/ 3522-8884',
                            :logradouro  => 'SES 813 Av. das Nações C. 3B',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Seu Estrelo E O Fuá Do Terreiro',
                            :email     => 'emaildoseuestrelo@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=qJHPc9_Ys20',
                            :latitude  => -15.8379947768173,
                            :longitude => -47.9084345698357,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Grupo musical baseado na percussão, trabalha com fabricação de instrumentos e pesquisa de ritmos afro brasileiros',
                            :site            => ' ',
                            :cep             => '71573-021',
                            :contato     => '8407-1813 / 3408-1813',
                            :logradouro  => 'Q. 30 Cj. A C. 26 - Paranoá, na rua da feira',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Organização Cultural E Ambiental TAMNOÁ',
                            :email     => 'tamboresdoparanoa@hotmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=NdG4I3Dk2YQ',
                            :latitude  => -15.7643023355814,
                            :longitude => -47.7777895331383,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Inclusão social através de música, percussão e expressão corporal, educação ambiental e inclusão digital.',
                            :site            => 'http://www.institutobatucar.org.br/',
                            :cep             => '72621-404',
                            :contato     => '8419-9701/8416-9674/8419-9675/patrici@batucar.org.br/ricardo@batucar.org,br',
                            :logradouro  => 'Q. 307 cnj.15  lote 17',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Batucar',
                            :email     => 'gilberto@batucar.org.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=qNNARzzo33g',
                            :latitude  => -15.9188207418712,
                            :longitude => -48.0989652872086,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de frevo, artes plásticas, corte e costura, cordel, serigrafia e construção de bonecos gigantes. O ponto possui também aulas de teoria musical e prática instrumental.',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3373 2741 / 8157-8180',
                            :logradouro  => 'QNM 03 Cj. C. 28',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Menino De Ceilândia',
                            :email     => 'meninodeceilandia@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=z_5LmmbZszs',
                            :latitude  => -15.821726085151,
                            :longitude => -48.1028115749359,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O ponto trabalha com diversas frentes: capoeira, mamulengo, cultura digital, cine clube, além da loja Mercado Brasileiro.',
                            :site            => ' ',
                            :cep             => '72015-630',
                            :contato     => '3352-5054  / 8408-2031',
                            :logradouro  => 'QSB 13, Área Especial Mercado Sul, Bl. B Lj. 5/24',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Invenção Brasileira',
                            :email     => 'clara@mamulengo.org',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=croWpeqb59Q',
                            :latitude  => -15.8416137342334,
                            :longitude => -48.0539739131927,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Brinquedoteca comunitária, oficinas de música, literatura e formação de oficineiros.',
                            :site            => 'www.ludocriarte.org',
                            :cep             => '71692-213',
                            :contato     => '9635-5566 / 85798582',
                            :logradouro  => 'Q. 103 Cj. 5 C. 1',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação LUDOCRIARTE',
                            :email     => 'ludopaolo@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=oPL3JuQFN4g',
                            :latitude  => -15.8983706170875,
                            :longitude => -47.7805495262146,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Divulgação da música brasileira',
                            :site            => ' ',
                            :cep             => '73010-120',
                            :contato     => '3901-6798',
                            :logradouro  => 'Teatro de Sobradinho quadra 12',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Banda Sinfônica De Sobradinho',
                            :email     => 'ndeicdreso@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=r3wLUBz1CL0',
                            :latitude  => -15.6491556053853,
                            :longitude => -47.7872657775879,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Produção de artesanato utilizando como matéria prima, fibras e plantas do cerrado. A associação também ministra cursos sobre o cerrado e técnicas de artesanato.',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '9144 7615/ 3388 7959',
                            :logradouro  => 'R. Marechal Deodoro quadra 54 nº 1073',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação Dos Artesãos De Planaltina',
                            :email     => 'associacaodosartesaosdeplanaltina@gmail.com',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=7gSl1GrJDHI',
                            :latitude  => -15.6224013847205,
                            :longitude => -47.658503651619,
                            :user_id  => 1,
                            :atividade_id  => 6,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de artesanato
',
                            :site            => 'www.cesom.org',
                            :cep             => ' ',
                            :contato     => '3552-0504/ 3552 0872',
                            :logradouro  => 'SMPW Trecho 03 Área Especial 1/2',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Integridade - Lar Dos Velhinhos Maria Madalena',
                            :email     => 'parqueassistencial@gmail.com',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=HUlJAGb6mM0',
                            :latitude  => -15.8676347720572,
                            :longitude => -47.975497841835,
                            :user_id  => 1,
                            :atividade_id  => 6,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Formação de formadores, desenvolvimento e execução de projetos culturais.',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3274-18519982 1560 (Laura)/ 3447 1560',
                            :logradouro  => 'SHIGS 709 BL J casa 55 parte A',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Cooperativa Brasiliense De Teatro',
                            :email     => 'lauracavalheiro@hotmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=rh8ASKhyO0A',
                            :latitude  => -15.8143144872037,
                            :longitude => -47.9097756743431,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Trabalho de formação musical através da prática vivencial.',
                            :site            => ' ',
                            :cep             => '72225-130',
                            :contato     => '8484-3046 / 9308 6867 / 3901-8205 / bandavitalogica@gmail.com',
                            :logradouro  => 'QNN 13 Área Especial',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Grupo Paralelo X Projeto 7 Bandas',
                            :email     => 'paralelox@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.8131738202284,
                            :longitude => -48.1182932853699,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Capoeira, Maculelê, Samba de roda. Também de desenvolve projetos de alfabetização (ABCerrado) e de artesanato (Bicho Serrador)',
                            :site            => 'amigosdocentrohistoricodf.blogspot.com',
                            :cep             => ' ',
                            :contato     => '9954 3601(Flávio) / 9164 2476 (Rui)',
                            :logradouro  => 'R. 15 de Novembro - Praça Salviano Monteiro',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Projeto Pau Pereira (Associação Dos Amigos Do Patrimônio Histórico De Planaltina)',
                            :email     => 'projeto.paupereira@gmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=pymvT2ErHsU',
                            :latitude  => -15.6209238341185,
                            :longitude => -47.6607191562653,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Capoeira, danças afro e circo',
                            :site            => ' ',
                            :cep             => '71825-105',
                            :contato     => '8602-8799 / 9311-2827 (Quixaba)',
                            :logradouro  => 'QS 10 Conj 5A C. 13',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Centro Cultural E Social Grito De Liberdade',
                            :email     => 'gritoquixaba@gmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=W9xQ9f7-e5U',
                            :latitude  => -15.8875617520426,
                            :longitude => -48.0225196480751,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Capoeira Angola',
                            :site            => 'http://nzambiangola.blogspot.com/',
                            :cep             => '70835-510',
                            :contato     => '8122 4207/ 9981-9227',
                            :logradouro  => 'CLN 403 Bl. A L. 54',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação Cultural De Capoeira Angola N ZAMBI',
                            :email     => 'biosal@gmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=oIMb4xfAl-E',
                            :latitude  => -15.7798232448632,
                            :longitude => -47.8765296936035,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Cursos e oficinas de artesanato',
                            :site            => 'www.pralapidar.org.br',
                            :cep             => ' ',
                            :contato     => '9902 2328 (Herlis)/ 9207 6382 (Elias) /3335 3343',
                            :logradouro  => 'Q. 201 Cj. 20 casa 7',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Grupo De Mulheres Mosaicistas De São Sebastião',
                            :email     => 'eliassilvaaraujo@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=9lCs2AL9OZw',
                            :latitude  => -15.9043500690679,
                            :longitude => -47.7766388654709,
                            :user_id  => 1,
                            :atividade_id  => 6,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Biblioteca Comunitária. Ponto de encontro de grupos de folia e quadrilhas de São Sebastião',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3339-4037/ 9200 6655',
                            :logradouro  => 'Av. 2 Q. 18 L. 16 - Residencial do Bosque',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Biblioteca Comunitária Do Bosque',
                            :email     => 'dilmadesm@hotmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=rf9-___Dbg8',
                            :latitude  => -15.9077550269829,
                            :longitude => -47.753786444664,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Centro de cultura popular e quadrilha junina, oferece cursos de artesanato, música e danças populares.',
                            :site            => ' ',
                            :cep             => '72302-106 / tatuhamilton@yahoo.com.br',
                            :contato     => '8115-7926/ 8419-3150/ 30412970',
                            :logradouro  => 'QS 106 Cj. 2 lote 1 loja 4',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Sócio Cultural Amigos Do Bem - ISABEM',
                            :email     => 'isabemdf@gmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=5MAHsHmabW8',
                            :latitude  => -15.8750547323813,
                            :longitude => -48.0798196792603,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de teatro música e luthieria',
                            :site            => 'ciaartcum-oboijatob.blogspot.com',
                            :cep             => '72145-516',
                            :contato     => '3964 2991',
                            :logradouro  => 'EQNM 36/38 bl. F lote 5 loja 1 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Ciartcum',
                            :email     => 'ciaartcum@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Xw7E6SZ6rJk',
                            :latitude  => -15.801429995957,
                            :longitude => -48.0985683202744,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Voltado para jovens, o programa oferece cursos de artes, principalmente grafite.',
                            :site            => 'www.picassonaopichava.ssp.df.gov.br',
                            :cep             => ' ',
                            :contato     => '8409-4727 / 3901-5805 (sede SiA trecho 8)',
                            :logradouro  => 'Ginásio de Esportes de Sobradinho',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Programa Picasso Não Pichava',
                            :email     => 'sedepnt@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Vz-45Sl5b34',
                            :latitude  => -15.6519553235868,
                            :longitude => -47.7868902683258,
                            :user_id  => 1,
                            :atividade_id  => 1,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oferece oficinas de teatro, inclusão digital e figurino',
                            :site            => 'www.mapati.com.br',
                            :cep             => '70740-741',
                            :contato     => '3347-3920/ 7813 4899',
                            :logradouro  => 'SHCGN 707 Bl. K C. 5',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação Artística Mapati',
                            :email     => 'mapati@mapati.com.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=vLETy2xISmg',
                            :latitude  => -15.7676399604442,
                            :longitude => -47.8914320468903,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O grupo oferece oficinas de percussão, violão e realiza palestras educativas.',
                            :site            => ' ',
                            :cep             => '72215-085',
                            :contato     => '3581-3590 / 8124-1913',
                            :logradouro  => 'QNM 07 Cj. O Lt. 15',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'ArteCei',
                            :email     => 'artecei@hotmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=8gNBHP4Uwvc',
                            :latitude  => -15.8312276040273,
                            :longitude => -48.0971775949001,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Ministra cursos de audiovisual e fotografia. Oferece telecentro com aulas de informática, redação, leitura e curso pré-vestibular',
                            :site            => ' ',
                            :cep             => '72225-505',
                            :contato     => '3372-1979',
                            :logradouro  => 'CNN 01 Bl. E',
                            :complemento => ' , 2º piso',
                            :estado    => 'DF',

                            :nome      => 'Casa Brasil',
                            :email     => 'casabrasilunbceilandia@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=a7TLIYNN08M',
                            :latitude  => -15.8213596406608,
                            :longitude => -48.1133741140366,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Projeto de integração sociocultural através da música. Confecção de instrumentos, danças afro e canto.',
                            :site            => 'www.sonsdecidadania.org.br',
                            :cep             => '71691-086',
                            :contato     => '3339-6978 / 3349-8622 / 9252-3972',
                            :logradouro  => 'Av. São Sebastião, NR 501, Bairro São José',
                            :complemento => ' , Casa Amarela',
                            :estado    => 'DF',

                            :nome      => 'Projeto Sons De Cidadania',
                            :email     => 'projeto@sonsdecidadania.org.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=gIOs6w-gjL8',
                            :latitude  => -15.9090705634602,
                            :longitude => -47.7674335241318,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de rádio jornalismo, informática, internet, interpretação de textos e educação ambiental. Produção e apresentação do programa de rádio aos domingos na Rádio Nacional AM.',
                            :site            => ' ',
                            :cep             => '72329-013',
                            :contato     => '8160 0780 / 9281-0395',
                            :logradouro  => 'QR 429 Cj. 13 Lt. 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Sociedade Dos Moradores E Amigos Da Expansão De Samambaia',
                            :email     => 'edvaldoferreira.jornalista@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=RgLidhehCg4',
                            :latitude  => -15.892625738905,
                            :longitude => -48.1413388252258,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Espaço programado para desenvolver atividades que unificam pesquisa, ensino e extensão entre alunos da Graduação e Pós-Graduação da UnB. Professor responsável: Dr. Osmar Abílio de C. Jr. Professor responsável pelo projeto de pesquisa: Dr. Neio Campos. Coordenação de Pesquisa: Me. Frederico S. Soares Desenvolvedores WEB: Diego Moreira e Anderson Augusto. ',
                            :site            => 'www.lsie.unb.br',
                            :cep             => '70910-900',
                            :contato     => '33072474',
                            :logradouro  => 'Campus Universitário Darcy Ribeiro ICC Norte BSS 664 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'LSIE - Laboratório De Sistemas De Informação Espacial',
                            :email     => 'lsie@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7605361485013,
                            :longitude => -47.8703498840332,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Propor, elaborar, e implementar políticas públicas culturais transdiciplinares, utilizando modelo de gestão compartilhada com entes públicos, privados e comunitários buscando o empoderamento das comunidades.',
                            :site            => 'www.arteria.org.br',
                            :cep             => ' ',
                            :contato     => '39640661',
                            :logradouro  => 'CLN 303 Bloco C sala 104 - Brasília-DF',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Artéria - Cultura E Cidadania',
                            :email     => 'secretaria@arteia.org',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7805149856646,
                            :longitude => -47.8855097293854,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Biblioteca e telecentro.',
                            :site            => ' ',
                            :cep             => '72630-420',
                            :contato     => '9674-4062 / 9124-2192 /  8592 9916',
                            :logradouro  => 'Av. Ponte Alta Q. 404 C. 77',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Biblioteca Comunitária Luís Lima',
                            :email     => 'luisrodrigues.lima@hotmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=M639xEzc1DY',
                            :latitude  => -15.9122020215336,
                            :longitude => -48.0593276023865,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Hip-Hop, break, grafite, discotecagem, MC, literatura, inclusão digital, rádioweb e estúdio musical.',
                            :site            => 'www.grupoatitude.org.br',
                            :cep             => '72215-043',
                            :contato     => '3877 3593 / 3372-8077',
                            :logradouro  => 'QNM 21 Cj. B. C. 20',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Atitude Jovem',
                            :email     => 'atitudeorg@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=g3npMMl_BXs',
                            :latitude  => -15.8277349058641,
                            :longitude => -48.096791356802,
                            :user_id  => 1,
                            :atividade_id  => 1,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Realização de espetáculos, oficinas de circo, teatro e confecção de bonecos.',
                            :site            => ' ',
                            :cep             => '72405-400',
                            :contato     => '3556-6606 / 3484 4001 / ciabagagem@gmail.com',
                            :logradouro  => 'Q. 40 Loja 16 - Setor Central',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Bagagem Cia De Bonecos',
                            :email     => 'eudesleao@hotmail.com',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=E60HPfVkTuQ',
                            :latitude  => -16.0214164866889,
                            :longitude => -48.0728888511658,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Educação ambiental e oficinas de teatro.',
                            :site            => ' ',
                            :cep             => '71881-665',
                            :contato     => '8172 2095 (Luciene) 8516 4530 (Sônia) / caradepano@hotmail.com',
                            :logradouro  => 'QN 16 Cj. 5 Lt. 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura 100 Dimensão',
                            :email     => 'sonia100x1000@hotmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=KfReKZvb_kk',
                            :latitude  => -15.8820926063382,
                            :longitude => -48.0539336800575,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Montagem de espetáculos teatrais e realização de oficinas e cursos de teatro.',
                            :site            => ' ',
                            :cep             => '70277-010',
                            :contato     => '3346-3025 / 8146-5733 / 9251-5373',
                            :logradouro  => 'SQS 411 Bl. A Ap. 207',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação Cultural Mandala',
                            :email     => 'teatromandala@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=s-1XtCBGm6Y',
                            :latitude  => -15.8283426164579,
                            :longitude => -47.9067850112915,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de capacitação voltadas para arte e educação, trabalhando com os elementos do Hip-Hop.',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => ' 9123 4904/ 3485 3912',
                            :logradouro  => 'AR 9 conj 5 loja 24',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Grupo Cultural Azulim',
                            :email     => 'iranazulim@hotmail.com',
                            :imagem    => File.open('db/imagens/Hip-Hop.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=0WKnKzaIWFM',
                            :latitude  => -15.6606744955528,
                            :longitude => -47.7928447723389,
                            :user_id  => 1,
                            :atividade_id  => 1,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oferece escola de esportes (lutas), dança, teatro e artesanato.',
                            :site            => 'http://www.ciecdf.org',
                            :cep             => ' ',
                            :contato     => '3389 4067 / 8590 6318 / 9303 2008',
                            :logradouro  => 'SRL 4 qd. 19 conj K lote 3 Buritis 4',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Centro De Integração Esporte E Cultura',
                            :email     => 'ciecdf@yahoo.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=dOuqMjNSy2c',
                            :latitude  => -15.6144917152448,
                            :longitude => -47.6800417900085,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oferece oficinas e cursos circenses',
                            :site            => ' ',
                            :cep             => '70800-110',
                            :contato     => '9114-9604 / 9979 4930',
                            :logradouro  => 'SCEN - Trecho 1- Clube da Imprensa',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Grupo Circo Teatro Artitude',
                            :email     => 'irmaossaude@hotmail.com',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=iyRH7mRgI7E',
                            :latitude  => -15.7889602277997,
                            :longitude => -47.843120098114,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 2,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Ponto promove oficinas de teatro, produz diversas montagens teatrais e fabrica bonecos de diversos tipos. O ponto conta com estúdio digital, telecentro e mala do livro.',
                            :site            => 'http://acaoculturaldogama.blogspot.com',
                            :cep             => '72420-160',
                            :contato     => '3385-5648 / 3384-6793',
                            :logradouro  => 'Qd. 12 lotes 32/34 loja 1 Setor Central do Gama (oficina)',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Pontinho De Cultura Rede Ação Cultural Do Gama Voar Teatro De Bonecos',
                            :email     => 'voarteatrodebonecos@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=TVcv5p3pHQE',
                            :latitude  => -16.0166135622447,
                            :longitude => -48.0707028508186,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Preservar e difundir a obra do artista plástico Athos Bulcão e contribuir para a formação social, cognitiva e produtiva de jovens e adolescentes. Promover, por meio da arte, cultura e comunicação, o desenvolvimento pessoal, social, cognitivo e produtivo do ser humano.',
                            :site            => 'http://fundathos.org.br',
                            :cep             => '70853-540',
                            :contato     => '3322 7801 ',
                            :logradouro  => 'CLN 208 Bloco D Entrada 49 Sala 111 Asa Norte ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Fundathos - Fundação Athos Bulcão',
                            :email     => 'undathos@fundathos.org.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7635821448265,
                            :longitude => -47.8816902637482,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'A Associação Cultural Claudio Santoro, entidade privada sem fins lucrativo, realiza trabalhos nas áreas de audiovisual e comunicação. ',
                            :site            => 'http://caminhosaudiovisuais.blogspot.com/',
                            :cep             => ' ',
                            :contato     => ' ',
                            :logradouro  => 'SEPN 509 Bloco D Loja 05 ',
                            :complemento => ' , ED: ISIS',
                            :estado    => 'DF',

                            :nome      => 'Associação Cultural Claudio Santoro',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7606412,
                            :longitude => -47.8912745,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => '\"O Ponto de Cultura Cinema a Céu Aberto, coordenado pela Tantri Arte e Cultura, realizará oficinas na área de cinema. A Tantri Arte realiza eventos culturais voltados para o intercâmbio entre culturas e valorização da cultura brasileira.\"',
                            :site            => ' ',
                            :cep             => '70200-610',
                            :contato     => '(61) 9637-6355',
                            :logradouro  => 'SGAS 601 s/n bl 2 md 3/4',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Cinema A Céu Aberto',
                            :email     => 'pontodeculturamediateca@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/user/doccrianca1',
                            :latitude  => -15.8060994,
                            :longitude => -47.8801876,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O grupo promove o Sarau Radical e o Projeto Expressa Periferia.Oferece cursos de audiovisual, comunicação e teatro ',
                            :site            => 'http://radicaislivressa.blogspot.com/',
                            :cep             => ' ',
                            :contato     => '8551-1075 ',
                            :logradouro  => 'Quadra 11, conjunto A, casa 42 B ',
                            :complemento => ' , Bairro Morro Azul',
                            :estado    => 'DF',

                            :nome      => 'Entidade: Associação Sociocultural Radicais Livres (Sarau Radical)',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=2hF-nRQWW6Q',
                            :latitude  => -15.8965648805088,
                            :longitude => -47.7845916152,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 1,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Brinquedoteca comunitária, oficinas de música, literatura e formação de oficineiros.',
                            :site            => 'www.ludocriarte.org',
                            :cep             => '71692-213',
                            :contato     => '9635-5566 / 8419-9701 / 8419-9675 / 8419 9674',
                            :logradouro  => 'Q. 103, Cj. 5, C. 1',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Associação Ludocriarte ',
                            :email     => 'ludopaolo@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.8984982,
                            :longitude => -47.7804789,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Entidade de estudo, pesquisa, montagem e apresentação de peças teatrais e produção de eventos culturais. Seu objetivo é o desenvolvimento de trabalhos voltados à pesquisa e experimentação de linguagens artísticas, dando especial atenção à linguagem cômica, à arte da bobagem e do palhaço.\"',
                            :site            => 'www.celeirodasantas.art.br',
                            :cep             => '72115-535',
                            :contato     => '(61)3526-8070 / (61) 8180-8080',
                            :logradouro  => 'CNC 03, Lote 15, Sala 102',
                            :complemento => ' , Parte A ',
                            :estado    => 'DF',

                            :nome      => 'Grupo De Teatro Celeiro Das Antas ',
                            :email     => 'contato@celeirodasantas.art.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.8222821,
                            :longitude => -48.0656029,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Desenvolve atividades da cultura popular brasileira- saraus,oficinas, recitais',
                            :site            => ' ',
                            :cep             => '72020-016',
                            :contato     => '(61) 9627-4382',
                            :logradouro  => 'QSB 13 Loja 01 - Mercado Sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Tribo Das Artes ',
                            :email     => 'tribodasartesbrasilia@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'www.facebook.com/tribodasartes',
                            :latitude  => -15.7943183346331,
                            :longitude => -47.882194519043,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => '\"Nossas atividades ligadas ao convênio com a Secretaria de Cultura são: apresentações teatrais em 06 localidades do  DF e produção de  programas de rádio com foco na cultura do DF e entorno. O CGB atualmente participa na execução de projetos de cultura e meio ambiente de parceiros em MG, GO e MT, sempre na área de comunicação  e produção de rádio e vídeo.\"',
                            :site            => 'www.gentebrasil.blogspot.com',
                            :cep             => ' ',
                            :contato     => '(18) 9131-3130 / (61) 3568-9752 / (61) 8446-4044 / ritharibeiro@gmail.com / acasarustica@gmail.com',
                            :logradouro  => 'QE40 conjunto M lote 03/101',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Coletivo Gente Brasil ',
                            :email     => 'gentebrasilradio@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7943183346331,
                            :longitude => -47.882194519043,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Grupo musical baseado na percussão, trabalha com fabricação de instrumentos e pesquisa de ritmos afro brasileiros ',
                            :site            => ' ',
                            :cep             => '71573-021',
                            :contato     => '(61) 8407-1813 / (61) 3408-1813',
                            :logradouro  => 'Q. 30 Cj. A C. 26 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Organização Cultural E Ambiental TAMNOÁ ',
                            :email     => 'tamboresdoparanoa@hotmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.9102408,
                            :longitude => -47.4882762,
                            :user_id  => 1,
                            :atividade_id  => 4,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Musica, Teatro, Dança e cultura popular.',
                            :site            => 'www.ferrock.org',
                            :cep             => '72235-403',
                            :contato     => '(61) 9127-8290',
                            :logradouro  => 'QNP 24 Conjunto C Lote 11 - Setor P Sul ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Ferrock De Canto A Canto ',
                            :email     => 'centroculturalferrock@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.8405101,
                            :longitude => -48.1283622,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Grupo Avesso é dedicado às atividades de cultura inseridas nas lutados dos trabalhadores e de registro dessas lutas em textos, vídeos e fotogrfias. Começou seu trabalho com as comunidades carentes com uma oficina de poesia na Cidade Estrutural de setembro a novembro de 2007. Em junho de 2008, iniciou parcerias com a comunidade do Condomínio Sol Nascente, apoiando a organização da festa junina e em novembro de 2009 apoiou a realização do desfile dos “Negros do Sol”. Em Setembro de 2009, iniciaremos as atividades dos ponto Cultura Avessa no Sol Nascente e, em outubro, na Cidade Estrutural, contemplando oficinas de vídeo, de software livre, cineclube e um espetáculo de raízes afro-brasileiras.',
                            :site            => 'www.videoavesso.org.br ',
                            :cep             => '72220-000',
                            :contato     => '(61) 3585-0715 / (61) 8480-3704',
                            :logradouro  => 'Chácara ADAN 92ª, lote 07, loja 1 - Setor Habitacional Sol Nascente ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Avessa',
                            :email     => 'videoavesso@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.816667,
                            :longitude => -48.116667,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Preservar e difundir a obra do artista plástico Athos Bulcão e contribuir para a formação social, cognitiva e produtiva de jovens e adolescentes. Promover, por meio da arte, cultura e comunicação, o desenvolvimento pessoal, social, cognitivo e produtivo do ser humano.     ',
                            :site            => 'http://fundathos.org.br     ',
                            :cep             => '70853-540',
                            :contato     => '(61) 33227-801',
                            :logradouro  => 'CLN 208 Bloco D Entrada 49 Sala 111 - Asa Norte ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Fundathos - Fundação Athos Bulcão',
                            :email     => 'undathos@fundathos.org.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.7622732,
                            :longitude => -47.8878045,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Atividades de capacitação, pesquisa, experimentação nas mais diversas linguagens artísticas  e cessão dos espaços (4 teatros, 4 galerias de arte, biblioteca de artes, gibiteca, \"galpão das artes\" para realização de oficinas de artes visuais) para artistas interessados em apresentar seus trabalhos.',
                            :site            => 'www.sc.df.gov.br',
                            :cep             => '70351-580',
                            :contato     => '(61) 3443-6039/ 961) 3244-0486     ',
                            :logradouro  => 'CRS 508 Sul Bloco A',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Pontão De Cultura 508 Sul',
                            :email     => 'pontao508sul@sc.df.gov.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => ' ',
                            :latitude  => -15.8124134,
                            :longitude => -47.9054797,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Instituto Cultural Congo Nya (ICCN), organização sem fins lucrativos foi criada para desenvolver projetos e atividades nas áreas de educação, artes, esportes e cultura, voltados principalmente para os/as jovens e crianças de São Sebastião-DF. ',
                            :site            => ' ',
                            :cep             => '71692-345',
                            :contato     => '(061) 3335.7151 / 8586.6201 ',
                            :logradouro  => 'Quadra 104, conjunto 09 , lote, 07',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Cultural Congo Nya (ICCN)',
                            :email     => 'congonya_iccn@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Z8lyzhfcJu8&feature=relmfu',
                            :latitude  => -15.9652900841325,
                            :longitude => -47.7252960205078,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Instituto Cultural Congo Nya (ICCN), organização sem fins lucrativos foi criada para desenvolver projetos e atividades nas áreas de educação, artes, esportes e cultura, voltados principalmente para os/as jovens e crianças de São Sebastião-DF. ',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '(061) 3335.7151 / 8586.6201 ',
                            :logradouro  => 'Quadra 104, conjunto 09 , lote, 07',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Instituto Cultural Congo Nya',
                            :email     => 'congonya_iccn@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Z8lyzhfcJu8&feature=relmfu',
                            :latitude  => -15.9666104009032,
                            :longitude => -47.7252960205078,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Ponto de Cultura se dedica a pesquisa, o ensino e difusão artística, o projeto está focado nas linguagens do clown (palhaço), de técnicas circenses e teatrais. Tem a parceria com a Universidade de Brasilia por meio do Decanato de extensão e do Departamento de Artes Cênicas.',
                            :site            => ' ',
                            :cep             => '72321-012',
                            :contato     => '(61) 9658-3110	',
                            :logradouro  => 'QR 407 Conj 12 Casa 23 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Galpão Do Riso ',
                            :email     => 'galpaodoriso@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=k8vxinnI4ag&feature=relmfu',
                            :latitude  => -15.8732813,
                            :longitude => -48.1022811,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas nas áreas de teatro, dança, artes visuais e música.',
                            :site            => 'www.ligadosblocos.com.br / www.mamaetagua.blogspot.com',
                            :cep             => ' ',
                            :contato     => ' ',
                            :logradouro  => 'QSC 08',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Mamãe Taguá',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=O_rRa-mlHXs&feature=relmfu',
                            :latitude  => -15.8388301,
                            :longitude => -48.0605715,
                            :user_id  => 1,
                            :atividade_id  => 2,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Ponto de Cultura Cinema a Céu Aberto, coordenado pela Tantri Arte e Cultura, realizará oficinas na área de cinema. A Tantri Arte realiza eventos culturais voltados para o intercâmbio entre culturas e valorização da cultura brasileira.',
                            :site            => 'www.tantriarte.com',
                            :cep             => '70874-520',
                            :contato     => '(61) 3427-0041 / (61) 8149-7800 ',
                            :logradouro  => 'SCLN 215, Bl B',
                            :complemento => ' , sala 114',
                            :estado    => 'DF',

                            :nome      => 'Ponto De Cultura Cinema A Céu Aberto',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=zh3RzkMVPaA&list=UUrKjUdCtg0JvcJNDAjzz4Ag&index=1&feature=plcp',
                            :latitude  => -15.7512966,
                            :longitude => -47.8852288,
                            :user_id  => 1,
                            :atividade_id  => 5,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'OSCIP Educação em Foco',
                            :site            => ' ',
                            :cep             => '70093-900',
                            :contato     => '3224.6557 / 7815.0577   ',
                            :logradouro  => 'SBS QD 1 Bloco K Sala 1213',
                            :complemento => ' , Ed Seguradoras',
                            :estado    => 'DF',

                            :nome      => 'OSCIP Educação Em Foco - Ação Periferia',
                            :email     => 'oscipeducacaoemfoco@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Y2smadLzLsA&list=UUrKjUdCtg0JvcJNDAjzz4Ag&index=3&feature=plcp',
                            :latitude  => -15.8008583365319,
                            :longitude => -47.8826934099197,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Reforço escolar, dança criativa e balé clássico.',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => ' (61) 3543-6736 / (61) 9902-6306',
                            :logradouro  => 'Centro de Ensino Infantil 01 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Projeto Garatuja ',
                            :email     => 'acehu@gmail.com',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=vRtX9aneYk4&list=UUrKjUdCtg0JvcJNDAjzz4Ag&index=4&feature=plcp',
                            :latitude  => -15.9671399,
                            :longitude => -47.7243139,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'Oficinas de Teatro, Edição, Roteiro, Camera e Futebol.',
                            :site            => 'www.resgatedavida.org.br',
                            :cep             => '71571-005',
                            :contato     => '(61) 9629-4400 / (61) 9556-7313 / (61) 9623-2770 / (61) 9283-5644/ (61) 8476-7463 / manoelcmagalhaes@ig.com.br / grupoaba@ig.com.br',
                            :logradouro  => 'Quadra 09 Conjunto E Casa 13 ',
                            :complemento => ' ,  ',
                            :estado    => 'DF',

                            :nome      => 'Giz No Teatro',
                            :email     => 'valxarope@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=RmhW3jRm5bY&list=UUrKjUdCtg0JvcJNDAjzz4Ag&index=5&feature=plcp',
                            :latitude  => -15.9102408,
                            :longitude => -47.4882762,
                            :user_id  => 1,
                            :atividade_id  => 3,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1

entidade = EntidadeEquipamento.create! :descricao => 'O Instituto Cultural Congo Nya (ICCN), organização sem fins lucrativos foi criada para desenvolver projetos e atividades nas áreas de educação, artes, esportes e cultura, voltados principalmente para os/as jovens e crianças de São Sebastião-DF.',
                            :site            => ' ',
                            :cep             => '71692-345',
                            :contato     => '(061) 3335.7151 / 8586.6201',
                            :logradouro  => 'Quadra 104 conjunto 09 ',
                            :complemento => '07, lote',
                            :estado    => 'DF',

                            :nome      => 'Instituto Cultural Congo NYA - ICCN',
                            :email     => 'congonya_iccn@yahoo.com.br',
                            :imagem    => File.open('db/imagens/Ponto-De-Cultura.png'),
                            :apresenta => 'http://www.youtube.com/watch?v=Z8lyzhfcJu8&list=UUrKjUdCtg0JvcJNDAjzz4Ag&index=7&feature=plcp',
                            :latitude  => -15.8933093544712,
                            :longitude => -47.7828669548035,
                            :user_id  => 1,
                            :atividade_id  => 7,
                            :tipo_entidade_id   => 3,
                            :publicar   => true, :tipo_id => 1
