# encoding: utf-8

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca e Galeria',
                            :horario         => '08:00 - 22:00 segunda a sexta / 08:00 - 18:00 sabado',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33878451',
                            :logradouro  => 'Q.08 Area Reservada',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica De Sobradinho & Galeria Vangogh',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6485150740628,
                            :longitude => -47.7945828437805,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'DF Digital',
                            :horario         => '08:00 - 12:00 / 14:00 - 17:00 de segunda a sexta',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3359-4539',
                            :logradouro  => 'A.E. QN 407/409',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Inezil Penna Marinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8740330850794,
                            :longitude => -48.1040132045746,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Residencia Oficial provisoria ',
                            :horario         => '09:00 - 17:00h de terca a domingo',
                            :site            => ' ',
                            :cep             => '71745-000',
                            :contato     => '33388694 / 33388803',
                            :logradouro  => 'BR 040 Km 0, Saida Sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Catetinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.9476300108013,
                            :longitude => -47.9884099960327,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => '08:00 - 18:00h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33943866',
                            :logradouro  => 'Qr 215/315 Cj B ',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Monteiro Lobato',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -16.0092684478399,
                            :longitude => -47.9961562156677,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Espaço Comercial',
                            :horario         => '08:00 - 18:00h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '39663378 / 39663377',
                            :logradouro  => 'Area Especial do Cave',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Casa Da Cultura',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8239144158857,
                            :longitude => -47.9726922512054,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34849900',
                            :logradouro  => 'Setor Central',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro Galpaozinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -16.0207565103633,
                            :longitude => -48.0680394172668,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '08:00 - 01:00h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '39663359',
                            :logradouro  => 'Area Especial do Cave',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio Do Cave',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8265259305233,
                            :longitude => -47.9743123054504,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Hospita de Campanha',
                            :horario         => '09:00 - 17:00h terca a domingo',
                            :site            => ' ',
                            :cep             => '71735-000',
                            :contato     => '33013590',
                            :logradouro  => 'Via EPIA sul lote D',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Vivo Da Memoria Candanga',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8600236110367,
                            :longitude => -47.9596781730652,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Inst. Candango de Solidariedade',
                            :horario         => '09:00 - 21:00h de segunda a sexta',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33013274',
                            :logradouro  => 'Area Especial 1 conj 1 Anexo da Adm. Regional',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Espaco Cultural Elva',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8545485575714,
                            :longitude => -47.9507625102997,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Teatro',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '39016798',
                            :logradouro  => 'Quadra 12',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro De Sobradinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.6492382544421,
                            :longitude => -47.7872711420059,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '08:00 - 18:00h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33872034',
                            :logradouro  => 'Quadra 02',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Agostinho Lima',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.6526268370135,
                            :longitude => -47.785120010376,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '35914100 / 33877963',
                            :logradouro  => 'Q. 2 Area Especial ',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio Esportivo De Sobradinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.6517487036273,
                            :longitude => -47.7870941162109,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Estadio',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33860080',
                            :logradouro  => 'Metropolitana',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Vasco Viana De Andrade',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8810813140665,
                            :longitude => -47.975857257843,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Cofre da Cidade',
                            :horario         => '08:00 - 22:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33013064',
                            :logradouro  => 'Rua dos Transportes Area Especial',
                            :complemento => ' , Praca da caixa forte',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica Da Candangolandia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8544556713108,
                            :longitude => -47.9511165618896,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => '08:00 - 21:45 de segunda a sexta',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33994843',
                            :logradouro  => 'A.C. 3 Lote 6',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Pública Do Riacho Fundo',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8825621331666,
                            :longitude => -48.0146688222885,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '07:30 - 21:30',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33613743',
                            :logradouro  => 'Q. 609 Area Especial',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio Poliesportivo Do Cruzeiro',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.7922432464882,
                            :longitude => -47.9393255710602,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'espaço cultural',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33822323',
                            :logradouro  => 'Area Especial do Cave',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Arco Da Cultura Djamilton Melo (espaco Cultural)',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8241311832068,
                            :longitude => -47.9756963253021,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Salao Multiuso',
                            :horario         => 'em funcao da demanda',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '39663378 / 39663377',
                            :logradouro  => 'Area Especial do Cave',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Salao Multiuso Do Guara',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8231196003863,
                            :longitude => -47.9726493358612,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Estadio',
                            :horario         => '16:00 - 18:00 para jogos',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '39663359',
                            :logradouro  => 'Area Especial do Cave',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Do Guara',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8265672190213,
                            :longitude => -47.9723167419434,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'bar',
                            :horario         => '08:00 - 21:45 segunda a sexta 08:00 - 17:00 sabados',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34869538',
                            :logradouro  => 'Praca Padre Roque Projecao 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica N. Bandeirante',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8715073236825,
                            :longitude => -47.9672795534134,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'polo de cinama',
                            :horario         => 'horaio comercial',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34873206',
                            :logradouro  => 'DF333 Km 4',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Polo De Cinama De Brasilia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6132207666718,
                            :longitude => -47.8147315979004,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 2,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'salao comunitario',
                            :horario         => 'horaio comercial',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33014768',
                            :logradouro  => 'Rua dos Transportes Area Especial',
                            :complemento => ' , Praca da caixa forte',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Salao Comunitario Da Candangolandia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8546104817213,
                            :longitude => -47.9511487483978,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Diretoria regional de cultura',
                            :horario         => 'comercial',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33861403',
                            :logradouro  => 'Rua 1 metropolitana',
                            :complemento => ' , setor dos engenheiros',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica Vo Philomena',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.881715952157,
                            :longitude => -47.9746288061142,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33860080',
                            :logradouro  => 'Praca Padre Roque Projecao 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio De Esportes Dilton Farias',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8713370464941,
                            :longitude => -47.9667270183563,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Centro Comunitario',
                            :horario         => '08:00 - 22:00 segunda a sexta 08:00 - 22:00h sabado',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33614524 / 33619907',
                            :logradouro  => 'Q.3 Area Especial ',
                            :complemento => ' , Cruzeiro Velho',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Centro Cultural Ruben Valentim',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.785785560084,
                            :longitude => -47.9372656345367,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'auditorio',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34849920',
                            :logradouro  => 'Area Especial Setor Central',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Auditorio Da Administração',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -16.0161056778085,
                            :longitude => -48.0645096302032,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Estadio',
                            :horario         => '08:00 - 18:00h ',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34849900',
                            :logradouro  => 'Setor Central',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Bezerrao',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -16.0112175463062,
                            :longitude => -48.0617201328278,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'secretaria do entorno',
                            :horario         => '08:00 - 22:00h segunda a sexta',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34849900',
                            :logradouro  => 'Q1 - Setor Industrial',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica Do Gama',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -16.017456595994,
                            :longitude => -48.0590486526489,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Cinema',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3484-9900',
                            :logradouro  => 'Setor Central',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Centro De Cultura Do Gama (itapua)',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -16.0175803437676,
                            :longitude => -48.0581474304199,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Eventos de cultura popular',
                            :horario         => 'Comercial',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3378-5067 / 3378-4891',
                            :logradouro  => 'QNN 32 Area Especial 6',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Casa Do Cantador',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8400113375599,
                            :longitude => -48.1085675954819,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3373-3305 / 3371-4842',
                            :logradouro  => 'QNN 12/14',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Abadião',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8282393961037,
                            :longitude => -48.1103110313416,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 7,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => 'Segunda a sexta: 7h30min às 19h - Sábados: 8h as 12h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3901-1360',
                            :logradouro  => 'QNN 11/13',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica De Ceilandia (carlos Drummond De Andrade)',
                            :email     => 'biblioteca@ceilandia.df.gov.br',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8154706317825,
                            :longitude => -48.1165874004364,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => 'Comercial',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3376-1043 / 3213-0155',
                            :logradouro  => 'P Sul',
                            :complemento => ' , Uzina de tratamento de lixo de Ceilandia',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Da Limpeza Urbana',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8453732526767,
                            :longitude => -48.1349122524261,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3359-9300',
                            :logradouro  => 'QN 303',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estádio Rorizao De Samambaia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8795746855496,
                            :longitude => -48.0887460708618,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Auditório',
                            :horario         => '4ª e 5ª de 8h às 22h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3354-4040',
                            :logradouro  => 'QNF 24 Area Especial',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro Yara Amral (sesi)',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.8124163828351,
                            :longitude => -48.0726246535778,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '8h - 17h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3441-9618 / 3441-9811',
                            :logradouro  => 'SIG Quadra 06',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Da Imprensa Nacional',
                            :email     => 'corex@in.gov.br',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7931207739195,
                            :longitude => -47.9128575325012,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Estadio',
                            :horario         => 'Dias de jogos (varia)',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3451-2500 / 3351-7077',
                            :logradouro  => 'Setor L Norte, Lt. 22/23',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Serejão',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8361872090967,
                            :longitude => -48.0808067321777,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 7,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '7h - 23h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3336-5912',
                            :logradouro  => 'Setor L Norte',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Serejinho',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8352272950374,
                            :longitude => -48.078339099884,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 7,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '8h - 19h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3336-9247',
                            :logradouro  => 'Centro Metropolitano de Taguatinga',
                            :complemento => ' , Academia da Policia Civil',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu De Armas E De Drogas',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8385405274893,
                            :longitude => -48.0919325351715,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Teatro',
                            :horario         => '24h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3352-0576',
                            :logradouro  => 'CNB 1',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro Da Praça',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.8322804335971,
                            :longitude => -48.058335185051,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => 'Segunda a sexta 8h - 22h
Sabado 9h - 17h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3351-7365',
                            :logradouro  => 'CNB 1',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica De Taguatinga',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8319294910167,
                            :longitude => -48.0582869052887,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Exposicao permanente',
                            :horario         => '9h - 18h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3325-6163',
                            :logradouro  => 'Praca dos 3 Poderes',
                            :complemento => ' , Esplanada dos Ministerios',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Espaco Lucio Costa',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8011009371171,
                            :longitude => -47.861670255661,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio poliesportivo',
                            :horario         => '8h - 12h / 14h - 18h (uso noturno para futsal)',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3451-2500 / 3351-7077',
                            :logradouro  => 'EQNM 36/38',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginásio De Esportes Bernardo Sayão',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.8009357622822,
                            :longitude => -48.0978119373322,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu da memoria de JK',
                            :horario         => 'Terca a domingo 9h - 18h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3226-7860 / 3225-9451',
                            :logradouro  => 'Eixo Monumental - Lado Oeste',
                            :complemento => ' , Praca do Cruzeiro',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Memorial Jk',
                            :email     => 'cultural@memorialjk.com.br',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7842420857811,
                            :longitude => -47.9133725166321,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3322-2025',
                            :logradouro  => 'Eixo Monumental/Setor de Divulgação Cultural, lote 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Complexo Cultural Funarte',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7892802728421,
                            :longitude => -47.896785736084,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3224-0599',
                            :logradouro  => 'SDC, Bloco G, Eixo Monumental',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Clube Do Choro',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7886608303668,
                            :longitude => -47.8992748260498,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Centro de convecoes',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3341-1603',
                            :logradouro  => 'SDC, Eixo Monumental',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Centro De Convencoes Ulysses Guimaraes',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7884130528464,
                            :longitude => -47.9006052017212,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => '07:30 - 23:00h segunda a sabado 08:00 - 14:00h sabado',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34430852 www.bdb.org.br',
                            :logradouro  => '506/7 W3 sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Demonstrativa De Brasilia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8102834135764,
                            :longitude => -47.9029226303101,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '09:00 - 18:30h Terca a domingo',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33255220',
                            :logradouro  => 'Setor Cultural Sul lote 2',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Nacional',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7972915582066,
                            :longitude => -47.8780746459961,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '32440411 508',
                            :logradouro  => 'Q. 508 W3 sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Espaco Cultural Renato Russo',
                            :email     => 'sul@sc.df.gov.br',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8125544508506,
                            :longitude => -47.9059481620789,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'espaco cultural',
                            :horario         => '09:00 - 21:00h terca a domingo',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '32069448 32069449',
                            :logradouro  => 'Setor Bancario Sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Complexo Cultural Da Caixa',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8037333928603,
                            :longitude => -47.8843751549721,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => 'segunda a sexta 09:00 - 21:00h e sabado e domingo 09:00 - 21:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33256237',
                            :logradouro  => 'Setor Cultural Sul ',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Nacional De Brasilia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7967727957787,
                            :longitude => -47.8801158070564,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Teatro',
                            :horario         => '09:00 - 00:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33256256 / 6440 / 6239',
                            :logradouro  => 'Setor Cultural Norte',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro Nacional Claudio Santoro',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.7922122748624,
                            :longitude => -47.8806924819946,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Cinema',
                            :horario         => '16:00 - 00:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33256215 32441660',
                            :logradouro  => '106/7 Sul',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Cine Brasilia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8142628734524,
                            :longitude => -47.8995323181152,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 2,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33211787',
                            :logradouro  => 'Torre de TV',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Nacional De Gemas',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7904365603961,
                            :longitude => -47.8930199146271,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Palacio',
                            :horario         => 'segunda a sexta 14:00 - 16:30h sabado a domingo 10:00 - 15:30',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '34118051',
                            :logradouro  => 'Esplanada dos Ministerios',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Do Itamati',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8006570294427,
                            :longitude => -47.867249250412,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33034331',
                            :logradouro  => 'SEnado Federal',
                            :complemento => ' , Esplanada dos Ministerios',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Do Senado',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7993149770661,
                            :longitude => -47.8637838363647,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu ',
                            :horario         => 'Interditado',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '32256244',
                            :logradouro  => 'Praca dos tres poderes',
                            :complemento => ' , Esplanada dos Ministerios',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Panteao Da Patria',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8015241970166,
                            :longitude => -47.8602647781372,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => '09:00 - 18:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33256163 33219843',
                            :logradouro  => 'Praca dos 3 Poderes',
                            :complemento => ' , Esplanada dos Ministerios',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Da Cidade',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8006570294427,
                            :longitude => -47.8618204593658,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'espaco cultural',
                            :horario         => 'em reforma',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '32266797',
                            :logradouro  => 'Praca dos tres poderes',
                            :complemento => ' , Esplanada dos Ministerios',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Espaco Oscar Niemeyer',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.8007396169907,
                            :longitude => -47.8608441352844,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Museu',
                            :horario         => 'fechado para reforma',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => ' ',
                            :logradouro  => 'SHTN lote 3 polo 5',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu De Arte Moderna',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7878194179714,
                            :longitude => -47.8334802389145,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Concha',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33256161 / 33558009',
                            :logradouro  => 'SHTN',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Concha Acustica ',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7866992500358,
                            :longitude => -47.8370904922485,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 6,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Cinema',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33072555 / 32745411',
                            :logradouro  => 'Campus Universitario Darcy Ribeiro',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Auditorio Dois Candangos',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.7679342263604,
                            :longitude => -47.8717446327209,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => 'segunda a sexta-feira 9:00 - 18:00h sabados domingos e feriados 10:00 - 18:00',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33441155 / 33441154 / 33421156',
                            :logradouro  => 'Eixo Monumental',
                            :complemento => ' , Praca do Buriti',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Memorial Dos Povos Indigenas',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.7848202447563,
                            :longitude => -47.9113984107971,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => '9h - 22h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3901-4478',
                            :logradouro  => 'St. Educacional Lt. C e D',
                            :complemento => ' , St. Central',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Comunitaria Monteiro Lobato',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6216316131839,
                            :longitude => -47.6536273956299,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio Multifuncoes',
                            :horario         => 'Ligado ao evento',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3388-4633',
                            :logradouro  => 'Av. WL2, St. Administrativo',
                            :complemento => ' , Administração Regional de Planaltina',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio De Esportes De Multiplas Funcoes',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.6156593277213,
                            :longitude => -47.6509881019592,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Prefeitura',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3389-2100',
                            :logradouro  => 'Rua Joao Quirino Q. 40 Lt. 1/3',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica Sebastiao Do Espirito Santo',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6189761375019,
                            :longitude => -47.6599144935608,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Residencial',
                            :horario         => '9h - 17h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3381-1700',
                            :logradouro  => 'Praca Salviano Monteiro nº 24',
                            :complemento => ' , St. Tradicional',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Museu Historico Artistico De Planaltina',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6211873142022,
                            :longitude => -47.6615345478058,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 4,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Estadio',
                            :horario         => '8h - 12h / 14h - 18h / eventos',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3389-2243 r. 219',
                            :logradouro  => 'Av. WL2, St. Administrativo',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Adonir Jose Guimaraes',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.6158866497309,
                            :longitude => -47.6527905464172,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Biblioteca',
                            :horario         => '8h - 22h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3901-6625',
                            :logradouro  => 'Area Especial 2',
                            :complemento => ' , Setor Sul',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Erico Verissimo',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6882345492087,
                            :longitude => -48.1959056854248,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '8h - 22h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3391-6030',
                            :logradouro  => 'Area Especial 4, Av. Alameda Veredinha Bloco. D',
                            :complemento => ' , St. Tradicional',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Biblioteca Publica Monteiro Lobato',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Cultura-Popular.png'),
                            :latitude  => -15.6808903857857,
                            :longitude => -48.198094367981,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 3,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => 'Dia de jogo',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3391-3656',
                            :logradouro  => 'Area Especial 4',
                            :complemento => ' , Setor Sul',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Estadio Chapadinha',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.68876133558,
                            :longitude => -48.1969141960144,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Ginasio',
                            :horario         => '8h - 12h / 14h - 0h',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3101-3677',
                            :logradouro  => 'Area Especial 1',
                            :complemento => ' , Setor Sul',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Ginasio Poliesportivo Espelho Dagua',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Artesanato.png'),
                            :latitude  => -15.6870260341582,
                            :longitude => -48.1964421272278,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 8,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => 'Teatro',
                            :horario         => 'Variavel',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '3379-9588 / 3379-9586',
                            :logradouro  => 'QNN 27 Lt. B A.E.',
                            :complemento => ' ,  ',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro Newton Rossi',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.8202706256508,
                            :longitude => -48.122992515564,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2

equipamento = EntidadeEquipamento.create! :descricao => ' ',
                            :horario         => '1',
                            :site            => ' ',
                            :cep             => ' ',
                            :contato     => '33911137',
                            :logradouro  => 'Avenida Veridiana',
                            :complemento => 'Em frente ao espelho dagua',
                            :estado    => 'DF', :apresenta => '',

                            :nome      => 'Teatro De Arena De Brazlandia',
                            :email     => ' ',
                            :imagem    => File.open('db/imagens/Teatro.png'),
                            :latitude  => -15.6823984915426,
                            :longitude => -48.199902176857,
                            :user_id  => 1,
                            :tipo_equipamento_id   => 1,
                            :publicar   => true, :tipo_id => 2
